In [1]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [11]:
arr2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr2.dtype)

int64


In [8]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
arr = np.array([1,2,3,4,5])
print("arr: ", arr)
print("arr.shape: ", arr.shape)
print("arr.dtype: ", arr.dtype)

print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))

arr:  [1 2 3 4 5]
arr.shape:  (5,)
arr.dtype:  int64
[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [15]:
a = np.array([1,2,3,4,5, 6, 7, 8, 9, 10])
print("Mean", np.mean(a))
print("Median", np.median(a))
print("Standard Deviation", np.std(a))

Mean 5.5
Median 5.5
Standard Deviation 2.8722813232690143
